### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by bgbruno** [syntax-tree/hast-util-select#2]
Hello - I try use it for search all elements

```
var body = '<!DOCTYPE html><html lang="en"><p></p></html>';
var h = require('hastscript');
var selectAll = require('hast-util-select').selectAll;
console.log(
    selectAll(
        'p',
        h('html', body)
    )
);
console.log(
    selectAll(
        'p',
        body
    )
);
console.log(
    selectAll(
        'p',
        h(body)
    )
);
```

but I get everytime only
```
[]
[]
[]
```

**Q can you help?**

Bruno

**Comment by ChristianMurphy** [comment]
```js
selectAll( 'p', h('html', body) )
```

Is searching for a paragraph in an empty document body.
No results is correct.

> search all elements

Use a universal (`*`) selector to get all elements
https://github.com/syntax-tree/hast-util-select/blob/master/readme.md#support
