### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ericdmoore** [syntax-tree/hast-util-select#4]
### Subject of the feature

Are you open to adding an index.d.ts file?

### Problem

I made a d.ts for this - that I have been using. Happy to PR it back to the project.

### Expected behavior

VS Code Intelisense to show expected types.

### Alternatives

I could submit directly to DefinitelyTyped - but I think their bots may ping you anyway. (Not sure, never PRd to `DT` before)

**Comment by ericdmoore** [comment]
Example is here: https://gist.github.com/ericdmoore/0d1219ae22df612fc394770990365522

**Comment by ChristianMurphy** [comment]
We are, you can see some examples of types being added in
https://github.com/syntax-tree/xast-util-sitemap/pull/1, https://github.com/syntax-tree/hast-util-sanitize/pull/21, and https://github.com/syntax-tree/mdast-util-to-string/pull/5
Note that for types as a dts file, using DTSLint and/or type coverage is highly recommended.

More recently there has been a push to get types generated from JSDoc
https://github.com/wooorm/zwitch/commit/88b233db64ec7a5c791699f947ae18168febb72d  and https://github.com/wooorm/zwitch/pull/6

Either works, and a PR would be welcome!

---

Closing this issue as we don't want to keep a types tracker issue in each of the 300+ unified repos.
