### ISSUE TITLE
Can't use parent-sensitive pseudoselectors with :not

### ISSUE THREAD

**Issue by apaleslimghost** [syntax-tree/hast-util-select#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hast-util-select@7.0.0

### Link to runnable example

https://runkit.com/quarterto/6397058cb17f2300086ba513

### Steps to reproduce

```js
import {h} from 'hastscript'
import {selectAll} from 'hast-util-select'

selectAll('img:not(:first-child)`, h('body', [
    h('img', { src: 'https://example.com/one' }),
    h('p', ['text']),
    h('img', { src: 'https://example.com/two' }),
]))
```

### Expected behavior

it selects the second `img`

### Actual behavior

```
Error: Cannot use `:first-child` without parent
```

this is because `:not` [is implemented using `matches`](https://github.com/syntax-tree/hast-util-select/blob/e88e19611e23cdca20a5c20ce5dbd267ab8247b2/lib/pseudo.js#L150), which doesn't support parent-sensitive pseudos

### Affected runtime and version

node@14, node@16

**Comment by wooorm** [comment]
Ah, interesting.
Want to work on a PR?
