### ISSUE TITLE
You are referencing a package which has no license, cause it is a Joke Project (https://github.com/Raynos/not)

### ISSUE THREAD

**Issue by haeferer** [syntax-tree/hast-util-select#8]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.0.2

### Steps to reproduce

Inspect the package.json for a reference to the "not" package in version 0.1.0

### Expected behavior

All Sub Packages are licensed correctly

### Actual behavior

Our licensing check Tool reports a "license not found" cause this joke-package has no license at all

### Affected runtime and version

npm

**Comment by remcohaszing** [comment]
Though I think the issue was put in a somewhat unrespectful manner, the `not` dependency is unused.

**Comment by wooorm** [comment]
PR welcome

**Comment by haeferer** [comment]
> Though I think the issue was put in a somewhat unrespectful manner, the `not` dependency is unused.

Sorry to all. I simply used the "issue form" which only includes direct questions, and no place to add a description or opinion. Respectful: you did a very good job by maintaining/ developing this. And answer so fast !

Best regard 

Andreas
